!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 4096
  - - callback
    - - custom_envs.info_logger_callback.LogAllInfoCallback
  - - ent_coef
    - 0.02
  - - env_wrapper
    - - stable_baselines3.common.monitor.Monitor
  - - gamma
    - 0.99
  - - learning_rate
    - 0.0003
  - - n_envs
    - 8
  - - n_timesteps
    - 10000000.0
  - - normalize
    - dict(norm_obs=True, norm_reward=True)
  - - normalize_advantage
    - true
  - - policy
    - MaskedMultiOutputPolicy
  - - policy_kwargs
    - dict( net_arch=dict(pi=[], vf=[128, 128]) )
