!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - ent_coef
    - 0.01
  - - env_wrapper
    - - custom_envs.lunarlander_continuous_multioutput.LunarLanderContinuousMultiOutput
  - - gae_lambda
    - 0.98
  - - gamma
    - 0.999
  - - n_envs
    - 16
  - - n_epochs
    - 4
  - - n_steps
    - 1024
  - - n_timesteps
    - 4000000.0
  - - policy
    - MaskedHybridPolicy
  - - policy_kwargs
    - dict( net_arch=dict(pi=[], vf=[64, 64]) )
