!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 512
  - - callback
    - - custom_envs.info_logger_callback.LogAllInfoCallback
  - - ent_coef
    - 0.001
  - - env_wrapper
    - - stable_baselines3.common.monitor.Monitor
  - - gamma
    - 0.96
  - - learning_rate
    - 0.0009
  - - n_envs
    - 8
  - - n_timesteps
    - 3000000.0
  - - normalize
    - dict(norm_obs=True, norm_reward=True)
  - - normalize_advantage
    - true
  - - policy
    - MultiOutputPolicy
  - - policy_kwargs
    - dict( net_arch=dict(pi=[64, 64], vf=[64, 64]) )
