!!python/object/apply:collections.OrderedDict
- - - callback
    - - custom_envs.info_logger_callback.LogAllInfoCallback
  - - ent_coef
    - 0.001
  - - env_wrapper
    - - stable_baselines3.common.monitor.Monitor
  - - gamma
    - 0.96
  - - learning_rate
    - lin_1e-4
  - - n_envs
    - 8
  - - n_timesteps
    - 3000000.0
  - - normalize
    - dict(norm_obs=True, norm_reward=True)
  - - normalize_advantage
    - true
  - - policy
    - MaskedMultiOutputPolicy
  - - policy_kwargs
    - dict( net_arch=dict(pi=[128, 128], vf=[128, 128]) )
